parameters = {
    "FEES": 0.002,  # 0.2%
    "LEVERAGE": 2,
    "DIGITS": 2,
    "MIN_LOT_SIZE": 0.01,
    "CANDLES_HISTORY_LENGTH": 12 * 6,  # 12 hours => 12 * HOURS
    "MIN_BUY_TAKE_PROFIT_PERCENTAGE": 0.01,
    "MIN_SELL_TAKE_PROFIT_PERCENTAGE": 0.01,
    "MAX_BUY_TAKE_PROFIT_PERCENTAGE": 0.03,
    "MAX_SELL_TAKE_PROFIT_PERCENTAGE": 0.03,
    # MAX_LOSS_PERCENTAGE : 0.00125,
    "START_TRADE_HOUR": 1,
    "END_TRADE_HOUR": 19,
    "START_CUSTOM_CLOSE_HOUR": 20,
    "END_CUSTOM_CLOSE_HOUR": 21
}
