parameters = {
    "FEES": 0.0007,  # 0.07%
    "LEVERAGE": 2,
    "DIGITS": 3,
    "CANDLES_HISTORY_LENGTH": 12 * 12,  # 12 hours => 12 * HOURS
    "MIN_BUY_TAKE_PROFIT_PERCENTAGE": 0.005,
    "MIN_SELL_TAKE_PROFIT_PERCENTAGE": 0.005,
    "MAX_BUY_TAKE_PROFIT_PERCENTAGE": 0.02,
    "MAX_SELL_TAKE_PROFIT_PERCENTAGE": 0.02,
    # MAX_LOSS_PERCENTAGE : 0.00125,
    "START_TRADE_HOUR": 1,
    "END_TRADE_HOUR": 19,
    "START_CUSTOM_CLOSE_HOUR": 20,
    "END_CUSTOM_CLOSE_HOUR": 21
}
