name: Topa deployment

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

on:
  push:
    branches:
      - topa-bot-demo
      - topa-bot-crypto-demo

jobs:
  set_branch_name:
    runs-on: self-hosted
    outputs:
      branchName: ${{ steps.set_branch_name_step.outputs.branchName }}
    steps:        
      - id: set_branch_name_step
        run: echo "branchName=${{ env.BRANCH_NAME }}" >> $GITHUB_OUTPUT

  deploy_topa_bot_demo:
    runs-on: self-hosted
    if: needs.set_branch_name.outputs.branchName == 'topa-bot-demo'
    needs: set_branch_name
    container:
      image: docker:25.0.1-dind
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: docker login -u ${{ secrets.PRIVATE_REGISTRY_USERNAME }} -p ${{ secrets.PRIVATE_REGISTRY_PASSWORD }} http://${{ secrets.PRIVATE_REGISTRY_IP }}:${{ secrets.PRIVATE_REGISTRY_PORT }}
      - run: docker build --pull --no-cache --build-arg environment=demo --build-arg devise=EURUSD -f dockerfiles/deploy.bot.dockerfile -t ${{ secrets.PRIVATE_REGISTRY_IP }}:${{ secrets.PRIVATE_REGISTRY_PORT }}/topa-bot-demo .
      - run: docker push ${{ secrets.PRIVATE_REGISTRY_IP }}:${{ secrets.PRIVATE_REGISTRY_PORT }}/topa-bot-demo

  deploy_topa_bot_crypto_demo:
    runs-on: self-hosted
    if: needs.set_branch_name.outputs.branchName == 'topa-bot-crypto-demo'
    needs: set_branch_name
    container:
      image: docker:25.0.1-dind
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: docker login -u ${{ secrets.PRIVATE_REGISTRY_USERNAME }} -p ${{ secrets.PRIVATE_REGISTRY_PASSWORD }} http://${{ secrets.PRIVATE_REGISTRY_IP }}:${{ secrets.PRIVATE_REGISTRY_PORT }}
      - run: docker build --pull --no-cache --build-arg environment=demo --build-arg devise=BTCUSD -f dockerfiles/deploy.bot.dockerfile -t ${{ secrets.PRIVATE_REGISTRY_IP }}:${{ secrets.PRIVATE_REGISTRY_PORT }}/topa-bot-crypto-demo .
      - run: docker push ${{ secrets.PRIVATE_REGISTRY_IP }}:${{ secrets.PRIVATE_REGISTRY_PORT }}/topa-bot-crypto-demo